version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_HOST=$DB_HOST"
      - "PMA_USER=$DB_USER"
      - "PMA_PASSWORD=$DB_PASS"
    links:
      - mysql
    ports:
      - 5555:80

  mysql:
    build: ./mysql/
    volumes:
      - db-store:/var/lib/mysql
      - db-log-store:/var/log/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: pkg

  app:
    build: ./
    volumes:
      - ./app:/app
    env_file:
      - ./.app.env
    ports:
      - "4567:4567"

volumes:
  db-store:
  db-log-store:
