# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "sinatra"
gem "haml"
gem "sequel"
gem "sqlite3"
gem "ed25519"
gem "net-ssh"
gem "mysql2"
